# Docker Compose Override for Development
# This file is automatically loaded by docker-compose and provides development-specific configurations
# It overrides settings from docker-compose.yml for local development convenience

services:
  # PostgreSQL Database - Development Configuration
  ajasta-postgres:
    environment:
      # Development database settings
      POSTGRES_DB: ajastadb_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "15432:5432"  # Fixed port for consistent development
    volumes:
      # Add volume mount for database initialization scripts
      - ./ajasta-postgres/init:/docker-entrypoint-initdb.d:ro
    command: 
      # Enable verbose logging for development
      - postgres
      - -c
      - log_statement=all
      - -c
      - log_destination=stderr
      - -c
      - log_min_messages=info

  # Spring Boot Backend - Development Configuration
  ajasta-backend:
    environment:
      # Development database connection
      DB_URL: jdbc:postgresql://ajasta-postgres:5432/ajastadb_dev
      DB_USERNAME: dev_user
      DB_PASSWORD: dev_password
      
      # Development JWT secret (not secure, only for dev)
      JWT_SECRET: dev-secret-key-not-for-production
      
      # Spring Boot development profile
      SPRING_PROFILES_ACTIVE: dev
      
      # Enable debug logging
      LOGGING_LEVEL_ROOT: INFO
      LOGGING_LEVEL_COM_AJASTA: DEBUG
      
      # JVM debugging options
      JAVA_OPTS: >-
        -XX:+UseContainerSupport 
        -XX:MaxRAMPercentage=75.0 
        -Dspring.devtools.restart.enabled=true
        -Dspring.devtools.livereload.enabled=true
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - "8090:8090"   # Application port
      - "5005:5005"   # Java debug port
    volumes:
      # Mount source code for development (if needed for file uploads or configs)
      - ./ajasta-backend/uploads:/app/uploads
      - ./ajasta-backend/logs:/app/logs
    # Override restart policy for development
    restart: "no"

  # React Frontend - Development Configuration  
  ajasta-frontend:
    environment:
      # Development API base URL (points to local backend)
      REACT_APP_API_BASE_URL: http://localhost:8090/api
      REACT_APP_ENVIRONMENT: development
      
      # Enable React development mode
      NODE_ENV: development
    ports:
      - "3000:80"     # Frontend port
    volumes:
      # Mount build output (if rebuilding frequently)
      - ./ajasta-react/build:/usr/share/nginx/html:ro
      # Mount nginx config for development
      - ./ajasta-react/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    # Override restart policy for development
    restart: "no"

# Additional development services
  # Adminer - Database administration tool
  adminer:
    image: adminer:4.8.1
    container_name: ajasta-adminer
    restart: "no"
    ports:
      - "8080:8080"
    networks:
      - ajasta-net
    environment:
      ADMINER_DEFAULT_SERVER: ajasta-postgres
      ADMINER_DESIGN: pepa-linha-dark

  # Mailhog - Email testing tool (for development mail testing)
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: ajasta-mailhog
    restart: "no"
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP
    networks:
      - ajasta-net

# Development-specific volumes
volumes:
  # Development data that can be easily reset
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./dev-data/postgres

# Network configuration remains the same
networks:
  ajasta-net:
    name: ajasta-net-dev