---
# Handlers for k8s_cluster role

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true

- name: Start kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true

- name: Stop kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: stopped

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true
