#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    # Do not set ssh-authorized-keys here; keys will be managed via instance metadata (ssh-keys)

