---
# ServiceAccount for read-only user
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader-user
  namespace: ajasta
---
# ServiceAccount for read-write user
apiVersion: v1
kind: ServiceAccount
metadata:
  name: writer-user
  namespace: ajasta
---
# ServiceAccount for admin user
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: ajasta
